### ISSUE TITLE
Transaction recovery handling finalizer does not permit wildflyserver to be terminated when there is no active pod

### ISSUE THREAD

**Issue by ochaloup** [wildfly/wildfly-operator#72]
Finalizer makes the operator removal being stuck when there is no active pod under operator management. The operator repeats error message[1] and never shuts down.
The activity may end up with panic.

```
{"level":"info","ts":1568704825.2354705,"logger":"controller_wildflyserver","msg":"WildflyServer is marked for deletion. Waiting for finalizers to clean the workspace","Request.Namespace":"default","Request.Name":"quickstart"}
{"level":"info","ts":1568704825.2425647,"logger":"controller_wildflyserver","msg":"Transaction recovery scaledown processing","Request.Namespace":"default","Request.Name":"quickstart","Pod Name":"quickstart-0","IP Address":"172.17.0.6"}
{"level":"info","ts":1568704825.2728443,"logger":"controller_wildflyserver","msg":"Enabling recovery listener for processing scaledown at quickstart-0","Request.Namespace":"default","Request.Name":"quickstart"}
{"level":"error","ts":1568704829.2799802,"logger":"controller_wildflyserver","msg":"Verify if operator JBOSS_HOME variable determines the place where the application server is installed","Request.Namespace":"default","Request.Name":"quickstart","quickstart.JBOSS_HOME":"/opt/jboss/wildfly","error":"Cannot execute JBoss CLI command /opt/jboss/wildfly/bin/jboss-cli.sh --output-json -c --command='/subsystem=transactions:write-attribute(name=recovery-listener, value=true)' at pod quickstart-0. Cause: cannot execute '/opt/jboss/wildfly/bin/jboss-cli.sh --output-json -c --command='/subsystem=transactions:write-attribute(name=recovery-listener, value=true)'': command terminated with exit code 1","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/jmesnil/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/wildfly/wildfly-operator/pkg/controller/wildflyserver.(*ReconcileWildFlyServer).checkRecovery\n\t/Users/jmesnil/Developer/wildfly-operator/pkg/controller/wildflyserver/wildflyserver_controller.go:968\ngithub.com/wildfly/wildfly-operator/pkg/controller/wildflyserver.(*ReconcileWildFlyServer).processTransactionRecoveryScaleDown.func1\n\t/Users/jmesnil/Developer/wildfly-operator/pkg/controller/wildflyserver/wildflyserver_controller.go:887"}
{"level":"error","ts":1568704829.2823055,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"wildflyserver-controller","request":"default/quickstart","error":"Finalizer processing: failed transaction recovery for WildflyServer default:quickstart name Error: Found 1 errors:\n [[Cannot enable transaction recovery listener for scaling down pod quickstart-0, error: Cannot execute JBoss CLI command /opt/jboss/wildfly/bin/jboss-cli.sh --output-json -c --command='/subsystem=transactions:write-attribute(name=recovery-listener, value=true)' at pod quickstart-0. Cause: cannot execute '/opt/jboss/wildfly/bin/jboss-cli.sh --output-json -c --command='/subsystem=transactions:write-attribute(name=recovery-listener, value=true)'': command terminated with exit code 1]],","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/jmesnil/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/jmesnil/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/Users/jmesnil/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/Users/jmesnil/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/jmesnil/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/Users/jmesnil/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:88"}

{"level":"info","ts":1568705107.4781928,"logger":"controller_wildflyserver","msg":"Reconciling WildFlyServer","Request.Namespace":"default","Request.Name":"quickstart"}
{"level":"info","ts":1568705107.483508,"logger":"controller_wildflyserver","msg":"WildflyServer is marked for deletion. Waiting for finalizers to clean the workspace","Request.Namespace":"default","Request.Name":"quickstart"}
{"level":"info","ts":1568705107.485902,"logger":"controller_wildflyserver","msg":"Transaction recovery scaledown processing","Request.Namespace":"default","Request.Name":"quickstart","Pod Name":"quickstart-0","IP Address":"172.17.0.6"}
{"level":"info","ts":1568705107.512193,"logger":"controller_wildflyserver","msg":"Enabling recovery listener for processing scaledown at quickstart-0","Request.Namespace":"default","Request.Name":"quickstart"}
{"level":"info","ts":1568705110.7030013,"logger":"controller_wildflyserver","msg":"Reloading WildFly for recovery listener being activated at pod quickstart-0","Request.Namespace":"default","Request.Name":"quickstart"}
{"level":"info","ts":1568705113.2886152,"logger":"controller_wildflyserver","msg":"Query to find the transaction recovery port to force scan at pod quickstart-0","Request.Namespace":"default","Request.Name":"quickstart"}
panic: assignment to entry in nil map

goroutine 378 [running]:
github.com/wildfly/wildfly-operator/pkg/controller/wildflyserver.(*ReconcileWildFlyServer).checkRecovery(0xc0004e5dd0, 0x1624960, 0xc000ac82e0, 0xc00027ea80, 0xc00091a1c0, 0x4, 0xc0000576e0, 0xc000057710, 0xebad1f, 0xc000611110)
        /Users/jmesnil/Developer/wildfly-operator/pkg/controller/wildflyserver/wildflyserver_controller.go:995 +0xa6e
github.com/wildfly/wildfly-operator/pkg/controller/wildflyserver.(*ReconcileWildFlyServer).processTransactionRecoveryScaleDown.func1(0xc0006a20e0, 0xc00027ea80, 0xc000aca300, 0xc000aca330, 0xc00091a1c0, 0x1624960, 0xc000ac82e0, 0xc0004e5dd0)
        /Users/jmesnil/Developer/wildfly-operator/pkg/controller/wildflyserver/wildflyserver_controller.go:887 +0x2e9
created by github.com/wildfly/wildfly-operator/pkg/controller/wildflyserver.(*ReconcileWildFlyServer).processTransactionRecoveryScaleDown
        /Users/jmesnil/Developer/wildfly-operator/pkg/controller/wildflyserver/wildflyserver_controller.go:866 +0x35c
```

**Comment by ochaloup** [comment]
@jmesnil I created the PR #75 to fix issues I found problematic when reproducing your issue. I was not able to really fully reproduce the panic but from what I could see I made the fix on the annotations map which I was wrongly expecting won't be nil.

There is still one big but...

The processing that you were experienced is intentional. I experimented with fixes which were not blocking the process in case when containers were not fully loaded but I found it's not the right way.

The processing has to wait for all containers would be started, then it checks whether it's clean from the transctions and then it can mark the pods to be removed and to allow the `wildflyserver` to be removed.
This all takes time (a bit more on this later).

The problematic scenario is for example this. The `wildflyserver` is defined with size of `1`. Some transactions are processing and a crash happens. There are some unfinished transactions in the log store. Now it could be the docker registry is unavailable for a while and the container waits for the image to be loaded and for the pod is to be started.
The operator can't let this pod go. It has no idea what's happening and it needs to wait for the pod would be fully functional and after that it can decide if the `wildflyserver` removal or the scaledown is possible.

Back to the fact that recovery takes time. It has two perspectives. First is that the ssh remote call is terribly slow. The recovery processing needs to run 5 CLI calls to get information about the state of the pod. Each of the takes like 3-5 seconds on my local machine. That means to verify the pod is ready to be removed is long lasting action.
The possible solution could be to return back to the REST API CLI calls (https://github.com/wildfly/wildfly-operator/commit/0df803aa3a34ffa49687eabddcb0d4e6fd226302#diff-f1b10e59cef6fe5581acc49be188ff9aR204). Those were much more faster in processing (in comparision to the ssh remote calls).
The other way to get it around is to create a better CLI command that would be capable to return all in-doubt transactions at one call as we talked about some time ago. Still it will be probably needed 2 or 3 CLI calls but it will much better.

From the discussion on the PR #54 I understood that you are not fan of REST API CLI calls. If so the second option would need for me to create a WFLY issue that I need to process and WFLY code update is needed. I don't know what is the exact slip for the WFLY18 but potentially I could be able to fix it in like two days at the start of the next week.
Or we can go with the state as it is and tune the speed later.

@jmesnil WDYT?

**Comment by jmesnil** [comment]
> This all takes time (a bit more on this later).

It's not taking time, it's hanging.
I've started a server with 2 pods and no activity.

I've executed `kubectl delete` 1 hour ago and it is still hanging.

**Comment by ochaloup** [comment]
@jmesnil 

> It's not taking time, it's hanging.
> I've started a server with 2 pods and no activity.
> I've executed kubectl delete 1 hour ago and it is still hanging.

I consider there was an error as mentioned here https://github.com/wildfly/wildfly-operator/pull/75#issuecomment-533563206 and tested by you.

My point of the whole comment was more complex. I didn't want to talk about an issue of the current code. I was talking if we can speed up the recovery processing. The https://issues.jboss.org/browse/JBEAP-17611 was created to get a single cli command being created. Still the ssh call will be slower than the direct rest jboss cli call.
